server:
  port: 8090

spring:
  application:
    name: config-service
# Para tomar en cuenta desde el servidor de config
# profiles:
#    active: native

# Para tomar desde la nube
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ivanyavila/java-academia-configs
          clone-on-start: true